apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green
  labels:
    app: blue-green
spec:
  selector:
    matchLabels:
      app: blue-green
  replicas: 1
  template:
    metadata:
      labels:
        app: "blue-green"
    spec:
      containers:
      - name: blue-green
        image: "adrianoneres/blue-green:blue"

---

apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
spec:
  selector:
    app: blue-green
  type: ClusterIP
  ports:
  - name: blue-green-service
    port: 8000
    targetPort: 80
    protocol: TCP
